# Generated by Django 5.1.7 on 2025-03-29 10:39

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('diploma', models.CharField(choices=[('None', 'None'), ('Bachelor (Бакалавр)', 'Bachelor (Бакалавр)'), ('Master (Магистратура)', 'Master (Магистратура)'), ('Postgraduate (Аспирантура)', 'Postgraduate (Аспирантура)'), ('PhD (Кандидат наук)', 'PhD (Кандидат наук)')], default='None', max_length=50)),
                ('phone_number', models.CharField(max_length=22)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Работник', max_length=10)),
                ('lvl', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
