# Generated by Django 5.1.7 on 2025-03-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='diploma',
            field=models.CharField(choices=[('None (Нету)', 'None (Нету)'), ('Bachelor (Бакалавр)', 'Bachelor (Бакалавр)'), ('Master (Магистратура)', 'Master (Магистратура)'), ('Postgraduate (Аспирантура)', 'Postgraduate (Аспирантура)'), ('PhD (Кандидат наук)', 'PhD (Кандидат наук)')], default='None', max_length=50),
        ),
    ]
