# Generated by Django 5.1.7 on 2025-03-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Ужасы', 'Ужасы'), ('Дедективы', 'Дедективы'), ('Научная фантастика', 'Научная фантастика'), ('Романтика', 'Романтика'), ('Психология', 'Психология'), ('Поэма', 'Поэма'), ('Детское\\Сказка', 'Детское\\Сказка'), ('Драма', 'Драма'), ('Другое', 'Другое')], max_length=30),
        ),
    ]
